belanja_1 = str(input('Masukkan daftar belanja 1: '))
belanja_2 = str(input('Masukkan daftar belanja 2: '))
tambahan_belanja_1 = str(input('Tambahkan data ke daftar belanja 1: '))
tambahan_belanja_2 = str(input('Tambahkan data ke daftar belanja 2: '))
print ('Daftar belanja 1 adalah', belanja_1,',', tambahan_belanja_1)
print ('Daftar belanja 2 adalah', belanja_2,',',tambahan_belanja_2)
